export const pageContent: Record<string, string> = {} as Record<string,string>;
pageContent['index'] = `
<section class="hero"><div class="container hero-grid"><div class="reveal"><span class="eyebrow">Trusted Homoeopathic Care in K.G.F</span><h1>Gentle care.<br/>Lasting wellness.</h1><p class="lead">Personalized homoeopathic consultation and genuine medicines, with a caring approach focused on natural healing and long-term wellness.</p><div class="actions"><a class="btn" href="/appointment">Book an Appointment →</a><a class="btn alt" href="/contact">Contact the Clinic</a></div></div><div class="hero-media"><div class="badge one"><span class="dot"></span> Personalized care</div><img alt="Doctor at Shruthi Homoeopathy" src="/image/Doctor_akka.png"/><div class="badge two">🌿 Natural healing</div></div></div></section>
<section class="info-strip"><div class="container info-grid"><div class="info"><span>Clinic</span><strong>Near Five Lights, K.G.F</strong></div><div class="info"><span>Consultation</span><strong>Mon–Sat · 10 AM–2 PM &amp; 4:30–8 PM</strong></div><div class="info"><span>Call</span><strong><a href="tel:+919632117374">+91 96321 17374</a></strong></div></div></section>
<section class="section"><div class="container split"><div class="photo contain"><img alt="Shruthi Homoeopathy" src="/image/SHRUTHI_logo-removebg-preview.png"/></div><div><div class="kicker">About Shruthi Homoeopathy</div><h2>Healthcare with a personal, caring touch.</h2><p class="lead">Shruthi Homoeopathy, located near Five Lights in K.G.F, Kolar District, offers trusted and personalized homoeopathic care. The clinic focuses on natural healing and treating root causes with safe remedies.</p><div class="checklist"><div class="check"><b>✓</b><span><strong>Personalized treatment</strong><br/>Care shaped around each patient's needs.</span></div><div class="check"><b>✓</b><span><strong>Quality medicines</strong><br/>Trusted homoeopathic pharmacy support.</span></div><div class="check"><b>✓</b><span><strong>Long-term wellness</strong><br/>Compassionate follow-up and patient education.</span></div></div><a class="btn" href="/about">Discover More →</a></div></div></section>
<section class="section soft"><div class="container"><div class="section-head"><div class="kicker">What We Do</div><h2>Natural care for everyday and long-term health.</h2><p>Personalized consultation, gentle remedies and ongoing care across the clinic's core services.</p></div><div class="grid cards-3">
<div class="card"><div class="icon">✦</div><h3>Natural Healing</h3><p>Gentle remedies that support natural healing and restore balance.</p></div>
<div class="card"><div class="icon">⌁</div><h3>Doctor Consultation</h3><p>Expert consultation with accurate diagnosis and personalized treatment.</p></div>
<div class="card"><div class="icon">♡</div><h3>Chronic Care</h3><p>Long-term care for chronic concerns including diabetes and arthritis.</p></div>
<div class="card"><div class="icon">◌</div><h3>Skin &amp; Allergy Care</h3><p>Personalized care for skin problems, allergies and related concerns.</p></div>
<div class="card"><div class="icon">☼</div><h3>Mental Wellness</h3><p>Support for stress, anxiety and sleep disorders through individualized care.</p></div>
<div class="card"><div class="icon">+</div><h3>Pain Relief</h3><p>Care for body pain, joint issues and inflammation with a lasting-wellness focus.</p></div>
</div><div class="actions"><a class="btn alt" href="/services">View All Services →</a></div></div></section>
<section class="section"><div class="container split"><div><div class="kicker">Our Doctor</div><h2>Experienced care from a dedicated doctor.</h2><p class="lead">At Shruthi Homoeopathy, the focus is on personalized and compassionate care, accurate diagnosis, root-cause treatment and long-term wellness.</p><p><strong>Dr. Sandra Shruthi S</strong><br/>BHMS, CGO · Homoeopathy Specialist</p><a class="btn" href="/doctor">Meet the Doctor →</a></div><div class="photo"><img alt="Dr. Sandra Shruthi S" src="/image/doctor.jpeg"/></div></div></section>
<section class="section mint"><div class="container"><div class="section-head center"><div class="kicker">Why Choose Us</div><h2>Care built around trust and continuity.</h2><p>Experience the clinic's stated approach to natural healing, patient care and long-term wellness.</p></div><div class="grid cards-4">
<div class="card"><h3>Natural Healing</h3><p>Safe and gentle remedies focused on natural care.</p></div><div class="card"><h3>Expert Consultation</h3><p>Personalized care with detailed diagnosis and treatment plans.</p></div><div class="card"><h3>Patient Care</h3><p>Compassionate treatment with personal attention to every patient.</p></div><div class="card"><h3>Long-Term Relief</h3><p>Focused on lasting results for chronic conditions and wellness.</p></div>
</div></div></section>
<section class="cta"><div class="container split"><div><div class="kicker" style="color:#bce3dc">Start Your Healing Journey</div><h2>Ready to talk to the clinic?</h2><p class="lead">Book a consultation or contact Shruthi Homoeopathy in K.G.F.</p></div><div class="actions"><a class="btn" href="/appointment">Book Appointment →</a><a class="btn alt" href="tel:+919632117374">Call +91 96321 17374</a></div></div></section>
`;
pageContent['about'] = `<section class="page-hero"><div class="container"><div class="kicker">About Us</div><h1>Care that listens before it treats.</h1><p class="crumb"><a href="/">Home</a> / About</p></div></section>
<section class="section"><div class="container split"><div><div class="kicker">Our Story</div><h2>Enhancing your health with safe, natural homoeopathic care.</h2><p class="lead">Shruthi Homoeopathy, located near Five Lights in K.G.F, Kolar District, offers trusted and personalized homoeopathic care. We focus on natural healing, treating root causes with safe remedies.</p><div class="checklist"><div class="check"><b>✓</b><span>Natural healing with a personal, caring touch.</span></div><div class="check"><b>✓</b><span>Safe, gentle treatments focused on root-cause cure.</span></div><div class="check"><b>✓</b><span>Trusted homoeopathic care for lasting health and wellness.</span></div></div></div><div class="photo contain"><img alt="Shruthi Homoeopathy logo" src="/image/SHRUTHI_logo-removebg-preview.png"/></div></div></section>
<section class="section soft"><div class="container"><div class="section-head center"><div class="kicker">Vision &amp; Mission</div><h2>A clear purpose for compassionate care.</h2></div><div class="grid cards-3"><div class="card"><div class="icon">◎</div><h3>Our Vision</h3><p>To be a trusted centre of excellence in homoeopathic healing, where compassionate care meets scientific precision—ensuring that safe, natural, and holistic healthcare is accessible to every individual, regardless of circumstances.</p></div><div class="card"><div class="icon">✦</div><h3>Our Mission</h3><p>At Shruthi Homoeopathy, we provide personalized, ethical, and affordable care focused on root-cause healing. We promote natural, holistic wellness through patient education, prevention, and compassionate treatment.</p></div><div class="card"><div class="icon">♡</div><h3>Our Promise</h3><p>To support patients with dignity, attentive consultation, quality medicines and a long-term wellness focus.</p></div></div></div></section>
<section class="section"><div class="container doctor"><div class="doctor-photo"><img alt="Dr. Sandra Shruthi S" src="/image/doctor.jpeg"/></div><div><div class="kicker">Meet Our Doctor</div><h2>Dr. Sandra Shruthi S</h2><p><strong>BHMS, CGO · Homoeopathy Specialist</strong></p><p class="lead">Expert in personalized treatment, focusing on natural healing and long-term health improvement.</p><a class="btn" href="/appointment">Book a Consultation →</a></div></div></section>`;
pageContent['service'] = `<section class="page-hero"><div class="container"><div class="kicker">Services</div><h1>Homoeopathic care, tailored to you.</h1><p class="crumb"><a href="/">Home</a> / Services</p></div></section><section class="section"><div class="container"><div class="section-head"><div class="kicker">What We Do</div><h2>Our homoeopathy services by expert.</h2><p>Shruthi Homoeopathy Clinic &amp; Pharmacy in KGF delivers personalized, safe, and natural treatments for skin, hair, allergy, and chronic conditions with long-term healing.</p></div><div class="grid cards-4">
<div class="card"><div class="icon">✦</div><h3>Natural Healing</h3><p>Gentle remedies that stimulate natural healing and restore balance.</p></div><div class="card"><div class="icon">⌁</div><h3>Herbal Treatment</h3><p>Natural-based remedies targeting root causes for safe and long-term recovery.</p></div><div class="card"><div class="icon">♡</div><h3>Care &amp; Healing</h3><p>Compassionate care with personalized treatments focused on holistic wellness.</p></div><div class="card"><div class="icon">↻</div><h3>Health Monitoring</h3><p>Regular follow-ups ensure steady recovery and improved overall health.</p></div><div class="card"><div class="icon">☼</div><h3>Mental Wellness</h3><p>Effective care for stress, anxiety, and sleep disorders naturally.</p></div><div class="card"><div class="icon">+</div><h3>Doctor Consultation</h3><p>Expert consultation with accurate diagnosis and personalized treatment.</p></div><div class="card"><div class="icon">◉</div><h3>Chronic Care</h3><p>Long-term management of chronic diseases like diabetes and arthritis using safe, natural remedies.</p></div><div class="card"><div class="icon">⌁</div><h3>Pain Relief</h3><p>Effective homoeopathic treatment for body pain, joint issues and inflammation with lasting relief.</p></div></div></div></section><section class="section soft"><div class="container split"><div><div class="kicker">Care Philosophy</div><h2>Root-cause care with patient attention.</h2><p class="lead">The clinic's approach combines personalized consultation, natural remedies and regular follow-up to support long-term wellness.</p><a class="btn" href="/appointment">Book Appointment →</a></div><div class="photo"><img alt="Calm natural care setting" src="/image/bg2.png"/></div></div></section>`;
pageContent['feature'] = `<section class="page-hero"><div class="container"><div class="kicker">Why Choose Us</div><h1>Get your healthy life back with thoughtful care.</h1><p class="crumb"><a href="/">Home</a> / Why Choose Us</p></div></section><section class="section"><div class="container"><div class="section-head center"><p>Experience natural healing with trusted homoeopathic care at Shruthi Homoeopathy, KGF.</p></div><div class="grid cards-4">
<div class="card"><div class="icon">✦</div><h3>Natural Healing</h3><p>Safe and gentle remedies that treat the root cause naturally.</p></div><div class="card"><div class="icon">⌁</div><h3>Expert Consultation</h3><p>Personalized care with detailed diagnosis and treatment plans.</p></div><div class="card"><div class="icon">☼</div><h3>Mental Care</h3><p>Effective support for stress, anxiety and sleep disorders.</p></div><div class="card"><div class="icon">♡</div><h3>Patient Care</h3><p>Compassionate treatment with personal attention to every patient.</p></div><div class="card"><div class="icon">◎</div><h3>Root Cause Treatment</h3><p>We treat the root cause, not just symptoms, with a focus on long-lasting results.</p></div><div class="card"><div class="icon">✓</div><h3>Trusted Clinic</h3><p>Reliable homoeopathy care near Five Lights, KGF, with a quality-care focus.</p></div><div class="card"><div class="icon">+</div><h3>Safe &amp; Gentle</h3><p>Gentle homoeopathic treatments with a focus on safe, individualized care.</p></div><div class="card"><div class="icon">↻</div><h3>Long-Term Relief</h3><p>Focused on lasting results for chronic conditions and long-term wellness.</p></div>
</div></div></section>`;
pageContent['team'] = `<section class="page-hero"><div class="container"><div class="kicker">Meet Our Doctor</div><h1>Experienced homoeopathy care from a dedicated doctor.</h1><p class="crumb"><a href="/">Home</a> / Doctor</p></div></section><section class="section"><div class="container doctor"><div class="doctor-photo"><img alt="Dr. Sandra Shruthi S, Homoeopathy Specialist" src="/image/doctor.jpeg"/></div><div><div class="kicker">Homoeopathy Specialist</div><h2>Dr. Sandra Shruthi S</h2><p><strong>BHMS, CGO</strong></p><p class="lead">Expert in personalized treatment, focusing on natural healing and long-term health improvement.</p><div class="checklist"><div class="check"><b>✓</b><span>Personalized and compassionate care.</span></div><div class="check"><b>✓</b><span>Focus on accurate diagnosis and root-cause treatment.</span></div><div class="check"><b>✓</b><span>Long-term wellness and patient support.</span></div></div><a class="btn" href="/appointment">Book Consultation →</a></div></div></section>`;
pageContent['testimonial'] = `<section class="page-hero"><div class="container"><div class="kicker">Our Treatment Approach</div><h1>Healing from the root, not just symptoms.</h1><p class="crumb"><a href="/">Home</a> / Treatment Approach</p></div></section><section class="section"><div class="container split"><div><div class="kicker">Our Philosophy</div><h2>Personalized care for long-term wellness.</h2><p class="lead">At Shruthi Homoeopathy, the stated approach focuses on identifying the root cause of illness rather than just treating symptoms. Treatments are personalized for each patient, with an emphasis on safe, gentle and long-lasting care.</p></div><div class="photo"><img alt="Natural healing environment" src="/image/bg3.png"/></div></div></section><section class="section soft"><div class="container"><div class="grid cards-3"><div class="card"><div class="icon">01</div><h3>Understand</h3><p>Detailed consultation and attention to the patient's concerns help shape individualized care.</p></div><div class="card"><div class="icon">02</div><h3>Personalize</h3><p>Care and remedies are selected around the individual's needs and treatment goals.</p></div><div class="card"><div class="icon">03</div><h3>Follow Up</h3><p>Regular follow-ups support steady recovery and ongoing health and wellness.</p></div></div></div></section><section class="cta"><div class="container split"><div><h2>Take the first step toward better health.</h2><p class="lead">Book a consultation with Shruthi Homoeopathy in K.G.F.</p></div><div class="actions"><a class="btn" href="/appointment">Book Appointment →</a></div></div></section>`;
pageContent['blog'] = `<section class="page-hero"><div class="container"><div class="kicker">Conditions We Treat</div><h1>Support for common and long-term concerns.</h1><p class="crumb"><a href="/">Home</a> / Conditions</p></div></section><section class="section"><div class="container"><div class="section-head"><p>Explore the range of health conditions treated at Shruthi Homoeopathy using personalized care and natural remedies.</p></div><div class="condition-grid">
<div class="condition"><h3>Skin Problems</h3><p><strong>Skin Disorders</strong><br/>Homeopathic treatment for skin conditions such as eczema, psoriasis, acne and fungal infections, with a focus on root-cause care.</p></div>
<div class="condition"><h3>Hair Fall</h3><p><strong>Hair Loss &amp; Dandruff</strong><br/>Personalized remedies for hair fall, dandruff and scalp conditions, addressing internal imbalances.</p></div>
<div class="condition"><h3>Allergy</h3><p><strong>Allergies &amp; Respiratory Issues</strong><br/>Care for allergies such as sinusitis, dust allergy and respiratory conditions using gentle homeopathic remedies.</p></div>
<div class="condition"><h3>Chronic Concerns</h3><p>Care for chronic diseases and concerns including diabetes, arthritis and other long-term conditions listed in the clinic's service information.</p></div>
<div class="condition"><h3>Thyroid Issues</h3><p>Personalized homeopathic care for thyroid-related concerns, as included in the clinic's stated treatment approach.</p></div>
<div class="condition"><h3>Joint &amp; Body Pain</h3><p>Care for body pain, joint issues and inflammation with an emphasis on long-term wellness.</p></div>
</div><div class="card" style="margin-top:20px"><strong>Important:</strong> Consultation is individualized. The information above describes the clinic's stated areas of care and is not a diagnosis or a guarantee of outcome.</div></div></section>`;
pageContent['404'] = `<section class="page-hero"><div class="container"><div class="kicker">404</div><h1>That page isn't here.</h1><p class="lead">Let's get you back to Shruthi Homoeopathy.</p><div class="actions"><a class="btn" href="/">Back to Home →</a><a class="btn alt" href="/contact">Contact Us</a></div></div></section>`;
pageContent['appointment'] = `<section class="page-hero"><div class="container"><div class="kicker">Appointments</div><h1>Book a consultation with Shruthi Homoeopathy.</h1><p class="crumb"><a href="/">Home</a> / Appointment</p></div></section><section class="section"><div class="container form-wrap"><div><div class="kicker">Before You Book</div><h2>Natural care, thoughtfully planned.</h2><p class="lead">At Shruthi Homoeopathy, consultations focus on personalized treatment and long-term wellness.</p><div class="checklist"><div class="check"><b>✓</b><span>Mon–Sat morning: 10:00 AM – 2:00 PM</span></div><div class="check"><b>✓</b><span>Mon–Sat evening: 4:30 PM – 8:00 PM</span></div><div class="check"><b>✓</b><span>Sunday: Holiday</span></div></div><p><strong>Need help?</strong><br/><a href="tel:+919632117374">+91 96321 17374</a></p></div><div data-form-slot="true"></div></div></section>`;
pageContent['contact'] = `<section class="page-hero"><div class="container"><div class="kicker">Contact</div><h1>We're here to help you connect.</h1><p class="crumb"><a href="/">Home</a> / Contact</p></div></section><section class="section"><div class="container form-wrap"><div><div class="kicker">Get In Touch</div><h2>Visit, call or send an enquiry.</h2><p class="lead">Shruthi Homoeopathy provides clinic and pharmacy services near Five Lights, K.G.F.</p><div class="card"><h3>Clinic &amp; Pharmacy</h3><p>Kolar K.G.F, Five Lights</p><p><a href="tel:+919632117374">+91 96321 17374</a><br/><a href="tel:+917676459212">+91 76764 59212</a></p><p><a href="mailto:shruthihomeopharmacy2011@gmail.com">shruthihomeopharmacy2011@gmail.com</a></p></div><div class="card" style="margin-top:18px"><h3>Working Hours</h3><p>Mon–Sat: 10:00 AM–2:00 PM<br/>Mon–Sat: 4:30 PM–8:00 PM<br/>Sunday: Holiday</p></div></div><div data-form-slot="true"></div></div></section><section class="section soft"><div class="container"><div class="section-head"><div class="kicker">Location</div><h2>Near Five Lights, K.G.F.</h2><p>The original site identifies the clinic and pharmacy location as Kolar K.G.F, Five Lights.</p></div><a class="btn" href="https://www.google.com/maps/search/?api=1&amp;query=Five+Lights+KGF" rel="noopener" target="_blank">Open Location in Maps →</a></div></section>`;
